
services:
  - type: web
    name: my-aspnetcore-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: PORT
        value: 10000

services:
  - type: web
    name: smoke-server
    runtime: dotnet
    buildCommand: dotnet build
    startCommand: dotnet Server.dll
    env: 
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
    region: oregon
    plan: free

